version: '3'
services:
  nextjs:
    build:
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - sail
    depends_on:
      - laravel.test

networks:
  sail:
    driver: bridge

